"""Mayhem Helper — English translations (UI strings and champion combo notes).
Loaded by haidou_helper.py when the interface language is English."""

EN = {'【战术建议】': '[Tactics]',
 '【推荐装备】': '[Recommended Items]',
 '海斗助手（控制台模式）。可输入：候选 A,B,C / 我的 X / 敌方 Y / 队友 Z，回车应用；Ctrl+C 退出': 'Mayhem Helper (console mode). Type: offer A,B,C / '
                                                                 'mine X / enemy Y / ally Z, Enter to apply; Ctrl+C '
                                                                 'to quit',
 '候选': 'Offer',
 '我的': 'Mine',
 '敌方': 'Enemy',
 '队友': 'Ally',
 '海斗助手': 'Mayhem Helper',
 '高分段': 'High elo',
 '全部分段': 'All ranks',
 '物理': 'AD',
 '可直接买': 'Buy now',
 '属性契合。': 'Stats fit.',
 '敌方后排': 'enemy backline',
 '普攻': 'AA',
 '闪现': 'Flash',
 '草丛': 'brush',
 '战局更新': 'Game update',
 '你': 'You',
 '对局已连接，给出首次推荐': 'Game connected, first recommendations',
 '阵容信息变化': 'Team comps changed',
 '【英雄玩法】': '[Playstyle]',
 '【三选一评分】': '[Augment Choice Scores]',
 '【推荐增幅】': '[Recommended Augments]',
 ' ←选它': ' ← pick this',
 '· 屏幕识别不可用：': '· Screen detection unavailable: ',
 '等待对局…': 'Waiting for game…',
 '出装': 'Build',
 '增幅': 'Augments',
 '玩法': 'Playstyle',
 '点一下切换 全部分段 / 高分段': 'Click to toggle All ranks / High elo',
 '小': 'Small',
 '中': 'Medium',
 '大': 'Large',
 '特大': 'X-Large',
 '字号': 'Text size',
 '一直自动识别三选一（较耗 CPU）': 'Always auto-detect augment choice (more CPU)',
 '手动输入增幅…': 'Enter augments manually…',
 '关闭海斗助手': 'Close Mayhem Helper',
 "<p class='s'>等待对局…</p>": "<p class='s'>Waiting for game…</p>",
 "<!doctype html><meta charset='utf-8'><meta name='viewport' content='width=device-width'><meta http-equiv='refresh' content='2'><title>海斗助手</title><style>body{background:#12161f;color:#e8ecf3;font-family:system-ui,sans-serif;margin:12px;font-size:16px}h3{margin:14px 0 6px}.c{background:#1a2030;border-radius:8px;padding:8px 10px;margin:6px 0}.t{display:flex;justify-content:space-between;font-size:17px}.t span{font-weight:700;font-size:20px}p{margin:4px 0;color:#9aa4b5;font-size:14px}.ch{color:#c8aa6e}.s{font-size:13px}</style><h2 style='color:#c8aa6e;margin:0'>⚔ 海斗助手</h2>": '<!doctype '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'html><meta '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "charset='utf-8'><meta "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "name='viewport' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "content='width=device-width'><meta "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "http-equiv='refresh' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "content='2'><title>Mayhem "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'Helper</title><style>body{background:#12161f;color:#e8ecf3;font-family:system-ui,sans-serif;margin:12px;font-size:16px}h3{margin:14px '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '0 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '6px}.c{background:#1a2030;border-radius:8px;padding:8px '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '10px;margin:6px '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '0}.t{display:flex;justify-content:space-between;font-size:17px}.t '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'span{font-weight:700;font-size:20px}p{margin:4px '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '0;color:#9aa4b5;font-size:14px}.ch{color:#c8aa6e}.s{font-size:13px}</style><h2 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "style='color:#c8aa6e;margin:0'>⚔ "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'Mayhem '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'Helper</h2>',
 '海斗助手：海克斯大乱斗实时出装/增幅推荐': 'Mayhem Helper: live build/augment recommendations for ARAM: Mayhem',
 '使用模拟对局演示': 'Run a simulated demo game',
 '控制台文字模式': 'Console text mode',
 '数据语言，默认 zh_MY（简体字＋台服用语，和游戏客户端一致），可改 zh_TW / zh_CN': 'Data language, default zh_MY (Simplified + TW terms, matches '
                                                      'game client); can be zh_TW / zh_CN',
 '轮询间隔秒数': 'Polling interval (seconds)',
 '悬浮窗透明度 0.3~1': 'Overlay opacity 0.3~1',
 '关闭屏幕识别三选一': 'Disable on-screen augment choice detection',
 '不使用网上胜率数据': "Don't use online win rate data",
 '不自动记录你点选的增幅': "Don't auto-record augments you pick",
 '识别三选一的快捷键（F1~F12），默认 F8': 'Hotkey to detect augment choice (F1~F12), default F8',
 '胜率数据分段：all 全部 / high 高分段': 'Win rate rank bracket: all = All ranks / high = High elo',
 '同时开启网页检视（手机/第二屏，埠 8765）': 'Also enable web view (phone/second screen, port 8765)',
 '界面缩放，例如 1.3': 'UI scale, e.g. 1.3',
 '没有装备/英雄数据：请确认能访问 ddragon.leagueoflegends.com 后重试': 'No item/champion data: check access to '
                                                     'ddragon.leagueoflegends.com and retry',
 '魔法': 'AP',
 '混合': 'Mixed',
 '差{0}g': '{0}g short',
 '。': '.',
 '与你的定位关系不大': 'Not very relevant to your role',
 '先开大招强化技能': 'Ult first to empower abilities',
 '再打出伤害': 'then deal damage',
 '新英雄，连招按技能描述推导，仅供参考': 'New champion; combo derived from ability text, for reference only',
 '造成伤害': 'Damage dealt',
 '承受伤害': 'Damage taken',
 '技能急速': 'Ability haste',
 '治疗': 'Healing',
 '护盾': 'Shielding',
 '韧性': 'Tenacity',
 '能量回复': 'Energy regen',
 '攻速': 'Attack speed',
 '海斗平衡：': 'Mayhem balance: ',
 '均势': 'Even',
 '增幅已重骰，重新评分': 'Augments rerolled, rescoring',
 '未安装 pillow': 'pillow not installed',
 '已连接，等待玩家数据…': 'Connected, waiting for player data…',
 '监控中': 'Monitoring',
 '重新读取胜率…': 'Reloading win rates…',
 '胜率数据分段': 'Win rate rank bracket',
 '检查更新中…': 'Checking for updates…',
 '三选一候选': 'Augment choice offers',
 '我的增幅': 'My augments',
 '队友增幅': 'Ally augments',
 '敌方增幅': 'Enemy augments',
 '，, ': ', ',
 '，': ', ',
 '识别到三选一（★ 推荐）': 'Augment choice detected (★ = pick)',
 '推荐增幅': 'Recommended augments',
 '[网页] 手机/平板连同一个 WiFi，浏览器开启：{0}': '[Web] Put phone/tablet on same WiFi, open in browser: {0}',
 '海斗助手 v{0}': 'Mayhem Helper v{0}',
 '未找到 tkinter，改用控制台模式': 'tkinter not found, using console mode',
 '[数据] 版本 {0}：装备 {1}，英雄 {2}，增幅 {3}': '[Data] Patch {0}: {1} items, {2} champions, {3} augments',
 '，游戏已是 {0}': ', game is already on {0}',
 'ARAMKit {0} {1}（{2:.0f}万场{3}）': 'ARAMKit {0} {1} ({2:.0f}0k games{3})',
 '这个英雄在海斗几乎没人出': 'Almost nobody builds this on this champ in Mayhem',
 '{0}（比平均{1:+.1f}%）': '{0} ({1:+.1f}% vs avg)',
 '网上胜率 {0:.1f}%': 'Win rate {0:.1f}%',
 '队伍缺前排，你需要更肉': 'Team lacks frontline, build tankier',
 '队伍缺魔法伤害，你的魔攻很关键': 'Team lacks magic damage, your AP is key',
 '{0}等': '{0} etc.',
 '对{0}{1}伤害有效生命 +{2}%': "Effective HP vs {0}'s {1} damage +{2}%",
 '先买{0}': 'Buy {0} first',
 '功能型增幅，不挑出装': 'Utility augment, build-agnostic',
 '和你现有装备属性吻合': 'Matches your current item stats',
 '血量低于 30% → 先吃血包或退后，别硬接团': "HP below 30% → grab a health relic or back off, don't force fights",
 '敌方回复强、我方没重伤 → 打爆发，别打持久战': 'Enemy sustain high, we lack anti-heal → burst them, avoid long fights',
 '你有保命类增幅 → 可以更积极进场': 'You have survivability augments → play more aggressively',
 '增幅强化大绝 → 以大绝为开团信号，大绝好了再打': "Augment empowers ult → ult is the engage signal, fight when it's up",
 '有跑速增幅 → 多绕侧翼找角度': 'You have move speed augments → flank for angles',
 '敌方有保命增幅 → 击杀要留一段伤害补刀': 'Enemy has survivability augments → save damage to finish kills',
 '按技能描述推导：': 'Derived from ability text: ',
 '无调整': 'No changes',
 '加点：主{0} 副{1}（{2}，{3:.0f}% 的人，胜率 {4:.1f}%）': 'Skills: max {0}, then {1} ({2}, {3:.0f}% of players, {4:.1f}% WR)',
 '召唤师：{0}（{1:.0f}% 的人，胜率 {2:.1f}%）': 'Summoners: {0} ({1:.0f}% of players, {2:.1f}% WR)',
 '领先 {0:.1f}k': 'Ahead {0:.1f}k',
 '｜网上胜率载入中…': ' | Loading win rates…',
 '已自动记录你选的增幅「{0}」': 'Auto-recorded your augment "{0}"',
 '识别到增幅三选一': 'Augment choice detected',
 '识别中…': 'Detecting…',
 '已载入网上胜率数据': 'Online win rate data loaded',
 '检查更新失败（连不上数据网站）': "Update check failed (can't reach data site)",
 '已是最新 ': 'Up to date ',
 '发现新版本，背景下载中…': 'New version found, downloading in background…',
 '数据已更新：': 'Data updated: ',
 ' 玩法：': ' Playstyle: ',
 '胜率{0:.1f}% ': 'WR {0:.1f}% ',
 ' {0}. {1:<10} {2:>3}分  [{3}{4}] {5}': ' {0}. {1:<10} {2:>3}pt  [{3}{4}] {5}',
 '[胜率{0:.1f}%] ': '[WR {0:.1f}%] ',
 ' {0}. {1:<10} {2:>3}分  {3}{4}{5}': ' {0}. {1:<10} {2:>3}pt  {3}{4}{5}',
 '\n点一下打开下载页，下载后解压覆盖旧文件': '\nClick to open the download page; extract and overwrite old files',
 '游戏数据 {0}': 'Game data {0}',
 '演示模式不检查更新': 'Demo mode skips update checks',
 '检查更新（当前 v{0}）': 'Check for updates (current v{0})',
 '网上 ': 'Online ',
 '当前局势推荐的增幅': 'Augments recommended for current game state',
 '已选增幅：': 'Picked augments: ',
 '连招  {0}\n        {1}': 'Combo  {0}\n        {1}',
 '玩法  ': 'Style  ',
 '（暂无这个英雄的玩法数据）': '(No playstyle data for this champion yet)',
 "<p class='ch'>[{0}] {1}</p><p class='s'>{2}</p><h3>英雄玩法</h3>{3}<h3>战术建议</h3>{4}<h3>推荐装备</h3>{5}<h3>{6}</h3>{7}": '<p '
                                                                                                                   "class='ch'>[{0}] "
                                                                                                                   '{1}</p><p '
                                                                                                                   "class='s'>{2}</p><h3>Playstyle</h3>{3}<h3>Tactics</h3>{4}<h3>Recommended "
                                                                                                                   'Items</h3>{5}<h3>{6}</h3>{7}',
 'augments.json 解析失败:': 'augments.json parse failed:',
 '无法连接胜率网站（{0}）': "Can't reach win rate site ({0})",
 '[胜率] ': '[Win rate] ',
 '英雄胜率下载失败（{0}）': 'Champion win rate download failed ({0})',
 '主流路线的下一件': 'Next item on the popular path',
 '」': '"',
 '你已有重伤装，重复收益低': 'You already have anti-heal, little value in more',
 '你的暴击已满，暴击属性浪费': 'Your crit is capped, extra crit wasted',
 '攻速已接近上限': 'Attack speed near cap',
 '我方领先，堆伤害滚雪球': "We're ahead, stack damage and snowball",
 '我方落后，先保命再反打': "We're behind, survive first then counter",
 '契合你的{0}路线': 'Fits your {0} path',
 '强化你的{0}': 'Boosts your {0}',
 '通用型增幅，效果不挑英雄': 'Generic augment, works on any champ',
 '描述未收录，按中性估算': 'Not in database, neutral estimate',
 '你是前排：先手开 {0}，吃掉技能给后排输出': "You're frontline: engage on {0}, soak skills for your backline",
 '你是战士：从侧面进场找 {0}，别当第一个吃技能的': "You're a fighter: flank in on {0}, don't eat skills first",
 '你是法师：保持距离消耗，技能留给 {0}': "You're a mage: keep distance and poke, save skills for {0}",
 '你是刺客：等对面交出控制再切 {0}，一套秒掉就走': "You're an assassin: wait for their CC, then dive {0} and get out",
 '你是辅助：保护{0}，护盾/补血优先给他': "You're support: protect {0}, shields/heals go to them first",
 '主C': 'carry',
 '{0}接近': '{0} to close in',
 '{0}控制': '{0} to CC',
 '，大招开团': ', ult to engage',
 '，大招收尾': ', ult to finish',
 '；胜率最高 {0}（{1:.1f}%）': '; best WR {0} ({1:.1f}%)',
 '＋': ' + ',
 '{0}｜非海斗模式': '{0} | Not Mayhem mode',
 '落后 {0:.1f}k': 'Behind {0:.1f}k',
 '{0}｜{1}｜人头 {2}:{3}｜敌方物理 {4}%': '{0} | {1} | Kills {2}:{3} | Enemy AD {4}%',
 '｜网上 {0} 级 胜率 {1:.1f}%': ' | Tier {0} · WR {1:.1f}%',
 '{0}{1}': '{0} {1}',
 '三选一界面已关闭': 'Augment choice screen closed',
 '未安装 OCR 库（运行 start.bat 会自动安装）': 'OCR library not installed (start.bat installs it automatically)',
 'OCR 初始化失败：{0}': 'OCR init failed: {0}',
 '宽度 {0}\n结果 {1}\n\n': 'Width {0}\nResult {1}\n\n',
 '[胜率] {0}：海斗增幅 {1} 个，商店成品装备 {2} 件': '[Win rate] {0}: {1} Mayhem augments, {2} finished shop items',
 '海斗增幅/装备/平衡调整': 'Mayhem augments/items/balance changes',
 '\n==== {0} ｜ ': '\n==== {0} | ',
 '；': '; ',
 ' 连招：{0}｜{1}': ' Combo: {0} | {1}',
 '识别 {0}': 'Detect {0}',
 '海斗胜率 ARAMKit {0}（{1}）': 'Mayhem WR ARAMKit {0} ({1})',
 '识别不可用：': 'Detection unavailable: ',
 '手动输入增幅（逗号或空格分隔，可只写关键字）': 'Enter augments manually (comma or space separated, keywords OK)',
 '套用并关闭': 'Apply and close',
 '主流路线的下一件，': 'Next item on the popular path, ',
 '未收录': 'Not listed',
 '识别到三选一 · ★ 推荐 · 点卡片记为已选': 'Augment choice detected · ★ = pick · click a card to mark picked',
 '三选一评分 · ★ 推荐 · 点卡片记为已选': 'Augment choice scores · ★ = pick · click a card to mark picked',
 '（还没有）': '(none yet)',
 '[数据] 无法获取版本号（{0}），尝试使用本地缓存': "[Data] Can't get patch version ({0}), trying local cache",
 '[胜率] 装备清单下载失败：{0}': '[Win rate] Item list download failed: {0}',
 '[胜率] 增幅描述下载失败：{0}': '[Win rate] Augment descriptions download failed: {0}',
 '[胜率] 增幅×装备数据下载失败：{0}': '[Win rate] Augment×item data download failed: {0}',
 '你这套核心后的常见选择': 'Common pick after your core',
 '{0}，胜率 {1:.1f}%': '{0}, WR {1:.1f}%',
 '和已选增幅组合胜率 {0:.1f}%': 'WR with picked augments {0:.1f}%',
 '「': '"',
 '、': ', ',
 '敌方人均已堆{0}物理防御，穿甲收益高': 'Enemies avg {0} armor, armor pen pays off',
 '敌方人均已堆{0}魔法防御，魔穿收益高': 'Enemies avg {0} MR, magic pen pays off',
 '敌方前排厚（{0}）': 'Enemy frontline tanky ({0})',
 '生命装多': 'lots of HP items',
 '敌方控制多（{0}）': 'Enemy has lots of CC ({0})',
 '敌方攻速装多（{0}件）': 'Enemy has many attack speed items ({0})',
 '敌方已有 {0} 个重伤来源，回复效果打折': 'Enemy has {0} anti-heal sources, healing reduced',
 '有{0}保护，可放心堆输出': 'Protected by {0}, safe to stack damage',
 '敌方 {0} 人阵亡（{1:.0f} 秒后有人复活）→ 立刻推塔、打团': '{0} enemies dead ({1:.0f}s until a respawn) → push towers and fight now',
 '我方少 {0} 人 → 退塔下守，等队友复活别接团': "We're down {0} → fall back to tower, wait for respawns, don't fight",
 '我方装备/人头领先约 {0:.1f}k → 主动找团、压塔，别给对面拖时间': "We're ~{0:.1f}k ahead in items/kills → force fights, siege, don't let "
                                          'them stall',
 '（最脆的输出位）': ' (squishiest carry)',
 '你是主C：站在{0}身后，打最近的安全目标': "You're the carry: stay behind {0}, hit the nearest safe target",
 '我方消耗型、敌方开团强（{0}）→ 拉开距离先磨血，别挤一起': "We poke, enemy engage strong ({0}) → keep distance and whittle, don't clump",
 '敌方控制多（{0}）→ 分散站位，别被一次控多人': 'Enemy has lots of CC ({0}) → spread out, avoid multi-man CC',
 '敌方前排厚（{0}）→ 打得到后排才进，打不到就先打前排': 'Enemy frontline tanky ({0}) → dive only if you reach the backline, else hit the '
                                 'front',
 '二段': 'recast',
 '黄牌': 'gold card',
 '红牌': 'red card',
 '{0}「{1}」': '{0} "{1}"',
 '｜威胁 {0}': ' | Threat {0}',
 '{0} 阵亡': '{0} died',
 '{0} 卖出 {1}': '{0} sold {1}',
 '{0} 选择增幅「{1}」': '{0} picked augment "{1}"',
 '手动输入的增幅已更新': 'Manual augments updated',
 '检查程序新版本失败': 'App update check failed',
 '游戏数据': 'Game data',
 '海斗胜率': 'Mayhem WR',
 '海斗资料': 'Mayhem data',
 '游戏 {0} → {1}': 'Game {0} → {1}',
 '海斗胜率 {0}（{1}）': 'Mayhem WR {0} ({1})',
 '⇪ 新版 v{0}': '⇪ New v{0}',
 '已关闭': 'Closed',
 '｜': ' | ',
 '游戏 {0}': 'Game {0}',
 '等待推荐…': 'Waiting for recommendations…',
 '带「{0}」时胜率 {1:.1f}%': 'WR with "{0}": {1:.1f}%',
 '敌方物理伤害占{0}%': 'Enemy physical damage {0}%',
 '敌方魔法伤害占{0}%': 'Enemy magic damage {0}%',
 '{0}已经打肥，爆发打得死你': '{0} is fed, can burst you down',
 '敌方爆发高（{0}）': 'Enemy burst high ({0})',
 '克制{0}的暴击（{1}件）': "Counters {0}'s crit ({1} items)",
 '敌方已有{0}件暴击装': 'Enemy has {0} crit items',
 '与增幅「{0}」联动': 'Synergy with augment "{0}"',
 '和已选「{0}」同一套路可叠加': 'Stacks with picked "{0}" (same build)',
 '敌方核心{0}阵亡 {1:.0f} 秒 → 趁现在开团': 'Enemy core {0} dead for {1:.0f}s → engage now',
 '我方落后约 {0:.1f}k → 避战清兵，等对面失误或技能交完再反打': "We're ~{0:.1f}k behind → avoid fights, clear waves, punish mistakes/used "
                                        'skills',
 '集火 {0}': 'Focus {0}',
 '；小心 {0} 切入，保留位移/保命': '; watch for {0} diving, keep a dash/escape',
 '敌方消耗型（{0}）→ 别在外面被磨，找 {1} 直接开': "Enemy is poke ({0}) → don't get whittled, engage {1} directly",
 '{0}「{1}」{2}': '{0} "{1}" {2}',
 '当前模式（{0}）不是海克斯大乱斗，暂停推荐': "Current mode ({0}) isn't ARAM: Mayhem, recommendations paused",
 '网上主流核心：{0}（胜率 {1:.1f}%）': 'Popular online core: {0} ({1:.1f}% WR)',
 '{0} 复活': '{0} respawned',
 '{0} 做出 {1}': '{0} built {1}',
 '{0} 购买 {1}': '{0} bought {1}',
 '没识别到三选一（截图已存）': 'No augment choice detected (screenshot saved)',
 '（清理旧缓存 {0} 个）': '(cleared {0} old cache files)',
 '海斗助手 v{} 已发布（你现在是 v{}）\n': 'Mayhem Helper v{} released (you have v{})\n',
 '游戏 {0} · ARAMKit {1} · {2} ⇄': 'Game {0} · ARAMKit {1} · {2} ⇄',
 '游戏 {0} · {1} ⇄': 'Game {0} · {1} ⇄',
 '★ 选 {0}（{1}）': '★ Pick {0} ({1})',
 '连招：{0}｜{1}': 'Combo: {0} | {1}',
 '玩法：{0}': 'Playstyle: {0}',
 '[数据] 下载失败 {0}: {1}': '[Data] Download failed {0}: {1}',
 '，队友重伤不够': ', allies lack anti-heal',
 '，急需重伤': ', need anti-heal badly',
 '网上胜率 {0:.1f}%（比平均{1:+.1f}%）': 'Win rate {0:.1f}% ({1:+.1f}% vs avg)',
 '（{0}/{1}，装备 {2:.1f}k）': ' ({0}/{1}, items {2:.1f}k)',
 '我方开团能力强（{0}）→ 跟着先手一起进': 'Our engage is strong ({0}) → follow the initiation in',
 '识别出错：{0}': 'Detection error: {0}',
 '已识别：': 'Detected: ',
 '分析出错：{0}': 'Analysis error: {0}',
 '程序已是最新 v{0}': 'App is up to date v{0}',
 '\n  下载：{0}': '\n  Download: {0}',
 '数据已更新 ✓': 'Data updated ✓',
 '等待': 'Waiting',
 '胜率{0:.1f}%': 'WR {0:.1f}%',
 '敌方回复强（{0}）': 'Enemy sustain strong ({0})',
 '，{0:.0f}% 的人买': ', {0:.0f}% of players buy',
 '更新出错：{0}': 'Update error: {0}',
 '· 海斗助手有新版本 v{0}：': '· Mayhem Helper new version v{0}: ',
 '数据已更新': 'Data updated',
 '物理攻击': 'AD',
 '魔法攻击': 'AP',
 '暴击': 'Crit',
 '物理防御': 'Armor',
 '魔法防御': 'MR',
 '生命': 'HP',
 '技能疾速': 'Ability haste',
 '魔力': 'Mana',
 '物理穿透': 'Lethality',
 '魔法穿透': 'Magic pen',
 '攻击特效': 'On-hit',
 '吸血续航': 'Lifesteal',
 '治疗护盾': 'Heal & shield',
 '跑速': 'Move speed',
 '大绝': 'Ultimate',
 '真实伤害': 'True damage',
 '百分比伤害': '%HP damage',
 '重伤': 'Anti-heal',
 '保命': 'Survivability',
 '克制暴击': 'Anti-crit',
 '克制攻速': 'Anti-attack-speed'}

EN.update({'下载 {0}…': 'Downloading {0}…', '{0} 校验不符（GitHub 可能还没同步，稍后再试）': '{0} checksum mismatch (GitHub may not have synced yet, try again later)', '更新中…': 'Updating…', '已更新到 v{0}，重新打开海斗助手生效': 'Updated to v{0}. Restart Mayhem Helper to apply', '已是最新文件，重新打开即可': 'Files already up to date, just restart', '更新失败：{0}': 'Update failed: {0}', '更新失败': 'Update failed', '已更新 ✓ 请重新打开': 'Updated ✓ please restart', '\n点一下直接更新（从 GitHub 下载并校验），重新打开生效': '\nClick to update directly (downloaded from GitHub and verified); restart to apply', '输入「更新」回车直接更新': 'Type "update" and press Enter to update', '更新': 'update'})
EN.update({'下载失败': 'Download failed', '[网页] 端口 {0} 被占用，网页检视没有开启（{1}）': '[Web] Port {0} is in use, web view not started ({1})', '快捷键 {0} 不支持，只能用 F1~F12': 'Hotkey {0} not supported, use F1–F12', '三选一已关闭': 'Augment choice closed'})
EN.update({'arammayhem.com 标注为这个英雄的强力组合': 'arammayhem.com lists this as a strong combo for this champion', 'arammayhem.com 标注为这个英雄的陷阱组合': 'arammayhem.com lists this as a trap combo for this champion', '增幅多语言名称 / 国服选取率 / 推荐组合：': 'Augment names / CN pick rates / combos: ', '[arammayhem] 对上 {0} 个增幅（多语言名称、国服选取率、推荐组合）': '[arammayhem] Matched {0} augments (multilingual names, CN pick rates, combos)', '[arammayhem] 读取失败：{0}': '[arammayhem] Load failed: {0}', '国服选取率 {0:.0f}%': 'CN pick rate {0:.0f}%'})
EN.update({'已清除习惯记录': 'Habit history cleared', '按我的习惯调整推荐（只存本机）': 'Adjust picks to my habits (stored locally)', '清除我的习惯记录': 'Clear my habit history', '，胜率 {0:.0f}%': ', {0:.0f}% WR', '你的{0}：{1} 局{2}': 'Your {0}: {1} games{2}', '你常出（{0} 局里出了 {1} 局，赢 {2} 局）': 'You often build this ({1} of {0} games, won {2})', '你常拿（出现 {0} 次选了 {1} 次，赢 {2} 局）': 'You often pick this (offered {0}, picked {1}, won {2})', '我的习惯（{0} 局）': 'My habits ({0} games)', '；常出 {0}': '; usual items: {0}'})
EN.update({'没找到正在运行的游戏客户端': 'League client not running', '读取客户端对局记录失败：{0}': 'Failed to read client match history: {0}', '从客户端读到 {0} 局大乱斗 / 海斗，新增 {1} 局': 'Read {0} ARAM/Mayhem games from the client, {1} new', '从游戏客户端导入历史对局': 'Import match history from the client', '读取客户端对局记录…': 'Reading client match history…'})
EN.update({'💰 复活前买：{0}（剩 {1}g · {2:.0f} 秒后复活）': '💰 Buy before respawn: {0} ({1}g left · respawn in {2:.0f}s)'})
EN.update({'前排': 'frontline', '魔法伤害': 'magic damage', '开团': 'engage', '治疗/保护': 'heal/shield', '海斗胜率 {0:.1f}%': 'Mayhem WR {0:.1f}%', '（{0} 级）': ' (tier {0})', '你 {0} 局 {1} 胜': 'you: {1} wins in {0} games', '补上队伍缺的{0}': 'fills missing {0}', '暂无数据': 'no data yet', '你现在的英雄': 'your current pick', '选英雄中': 'Champ select', '选英雄': 'Champ select', '队伍缺：{0}': 'team lacks: {0}', '★ 建议从备选席换成 {0}（{1} 分，你现在的 {2} {3} 分）': '★ Swap to {0} from the bench ({1} vs your {2} at {3})', '保持 {0} 就好（备选席里没有明显更好的）': 'Keep {0} (nothing clearly better on the bench)', '★ 推荐 {0}': '★ Recommended: {0}', '\n==== 选英雄 ====': '\n==== Champ select ===='})
EN.update({'赢了': ' won', '输了': ' lost', '结束': ' ended', '复盘：{0}{1} · {2} 分钟': 'Review: {0}{1} · {2} min', '出装 {0}/{1} 件照推荐': '{0}/{1} items as recommended', '增幅 {0}/{1} 次选了 ★': '{0}/{1} augments picked ★', '这个英雄 {0} 局 {1} 胜': '{1} wins in {0} games on this champ', '没照推荐的：{0}': 'Not recommended: {0}', '还没有记录。打几局海斗，或在「我的习惯」里从游戏客户端导入历史对局。': 'No games yet. Play some Mayhem, or import your history from the client under "My habits".', '总计 {0} 局，胜率 {1}': 'Total {0} games, WR {1}', '照推荐出装（≥60% 的装备）：{0} 局，胜率 {1}\u3000｜\u3000没照：{2} 局，胜率 {3}': 'Followed item recs (≥60%): {0} games, WR {1}   |   Did not: {2} games, WR {3}', '英雄            局数  胜率   常出装备': 'Champion        Games  WR    Usual items', '最近 10 局': 'Last 10 games', '胜': 'W', '负': 'L', '我的战绩': 'My stats', '我的战绩…': 'My stats…'})
EN.update({'自建数据库：本次新增 {0} 局': 'Own database: +{0} games this session', '自建数据库：没有可以继续查的玩家（打一局后会再从你开始）': 'Own database: no more players to crawl (restarts from you after your next game)', 'Riot 密钥无效或已过期（开发者密钥每 24 小时要更新一次）': 'Riot key invalid or expired (development keys must be renewed every 24h)', '自建数据库出错：{0}': 'Own database error: {0}', '自建库': 'Own DB', '自建库·{0}': 'Own DB · {0}', '{0} {1} 局里出现 {2} 次，胜率 {3:.0f}%（{4:+.0f}%）': '{0}: in {2} of {1} games, WR {3:.0f}% ({4:+.0f}%)', '黑铁': 'Iron', '青铜': 'Bronze', '白银': 'Silver', '黄金': 'Gold', '铂金': 'Platinum', '翡翠': 'Emerald', '钻石': 'Diamond', '大师': 'Master', '宗师': 'Grandmaster', '王者': 'Challenger', '未定级': 'Unranked', '自建数据库（Riot 开发者密钥）': 'Own database (Riot dev key)', '用你自己的 Riot 开发者密钥，在不打游戏时于背景收集海斗对局，攒够数据后按你的段位给出装 / 增幅加权。密钥只存在本机。到 developer.riotgames.com 登录后即可免费取得（开发者密钥每 24 小时要更新一次）。': 'Use your own Riot development key to collect Mayhem matches in the background while you are not in game; once there is enough data, item/augment picks are weighted by your rank. The key stays on this computer. Get one free at developer.riotgames.com (development keys expire every 24h).', 'Riot 开发者密钥（RGAPI-…）': 'Riot development key (RGAPI-…)', '你的服务器': 'Your server', '你的 Riot ID（名字#TAG，留空＝进游戏时自动读取）': 'Your Riot ID (Name#TAG; blank = read automatically in game)', '启用收集（只在不打游戏时）': 'Enable collection (only when not in game)', '记录每个玩家的段位（可以按段位统计，收集速度约慢 10 倍）': "Record each player's rank (enables per-rank stats, ~10× slower)", '已收集约 {0} 局': 'Collected ~{0} games', '\u3000你的段位：{0}': '   Your rank: {0}', '保存': 'Save', '已保存，会在不打游戏时开始收集': 'Saved; collection starts when you are not in game', '自建数据库（Riot 密钥）…': 'Own database (Riot key)…'})

EN.update({'平A': 'AA', '闪': 'Flash', '草': 'Bush', '连招': 'Combo', '战局': 'Game', '威胁': 'Threat', '敌少{0}人 → 推': 'Enemy -{0} → push', '我少{0}人 → 退守': 'We are -{0} → fall back', '残血 → 后撤': 'Low HP → back off', '{0}阵亡 → 开团': '{0} dead → engage', '领先{0:.1f}k': '+{0:.1f}k', '落后{0:.1f}k': '-{0:.1f}k', '爆发': 'burst', '控制': 'CC', '回复': 'sustain', '消耗': 'poke', '坦': 'tank', '战士': 'fighter', '输出': 'carry', '刺客': 'assassin', '辅助': 'support', '(亡)': ' (dead)', '先手开团': 'Start fights', '侧翼进场': 'Flank in', '躲前排后输出': 'DPS behind frontline', '远距消耗': 'Poke from range', '等控制交完再切': 'Dive after CC is used', '保护主C': 'Peel for carry', '打{0}': 'hit {0}', '显示战况条（连招 / 战局 / 威胁 / 玩法）': 'Show status strip (combo / game / threat / plan)'})
EN.update({'已有重伤': 'already have anti-heal', '出重伤': 'buy anti-heal', '留伤害补刀': 'save damage to finish', '双抗没用，堆血': 'resists useless, stack HP', '别堆血，出双抗': "don't stack HP, buy resists", '躲他大招': 'dodge his ult', '控制会变短': 'your CC is shorter', '出破甲': 'buy armor pen', '打别人': 'hit someone else', '出百分比伤害': 'buy %HP damage', '出法穿': 'buy magic pen', '出护甲': 'buy armor', '出魔抗': 'buy MR', '留控制给他': 'save CC for him', '别站一起': "don't group up", '敌增幅': 'Enemy aug', '敌方增幅：': 'Enemy augments:', '游戏没提供敌方增幅：可在 ⋯ → 手动输入增幅 填写': 'Game does not expose enemy augments: enter them via ⋯ → Enter augments manually'})
EN.update({'「{0}」让你变近战，这件的远程效果用不上': '[{0}] makes you melee; this item\'s ranged effect is wasted', '「{0}」让你变近战，近战效果全额': '[{0}] makes you melee; full melee effect'})
EN.update({'「{0}」': '[{0}] ', '物攻会转成魔攻，穿甲用处变小': 'AD converts to AP, armor pen is worth less', '物攻转成魔攻，法穿更值': 'AD converts to AP, magic pen is worth more', '魔攻会转成物攻，法穿用处变小': 'AP converts to AD, magic pen is worth less', '魔攻转成物攻，穿甲更值': 'AP converts to AD, armor pen is worth more', '攻速会转成技能急速，攻速装的普攻效果白费': 'attack speed converts to haste, attack-speed item effects are wasted', '攻速被转掉，命中效果打不出来': 'attack speed is converted away, on-hit is wasted', '技能急速吃满': 'ability haste fully used', '技能急速只对大绝生效（已送 100）': 'haste only affects your ult (100 given)', '已送 70 技能急速，再堆收益递减': '70 haste given, more has diminishing returns', '技能效果随最大魔力增强': 'abilities scale with max mana', '最大魔力的一半会变成生命': 'half your max mana becomes health', '普攻按最大魔力加伤（可暴击）': 'attacks deal bonus damage from max mana (can crit)', '暴击率同时是格挡几率': 'crit chance also gives block chance', '你变近战，这件的远程效果用不上': "you become melee; this item's ranged effect is wasted", '你变近战，近战效果全额': 'you become melee; full melee effect', '多的暴击率会转成暴击伤害，无尽更值': 'excess crit converts to crit damage, IE is worth more', '暴击率有上限，再堆暴击率收益变小': 'crit chance is capped, more crit is worth less'})
EN.update({'你变近战了：贴脸打，靠吸血和血量站得住，别在外面晃': "You're melee now: fight up close, lean on lifesteal and HP, don't hover outside", '绑在你选的那个技能上：多按那个技能': 'Tied to the ability you chose: use that ability a lot', '靠位移触发：多用位移技能穿进穿出': 'Triggered by dashes: use your mobility often', '命中控制才触发：先控住再打': 'Triggers on CC: land your CC first, then hit', '参与击杀才叠层：多跟团、补残血': 'Stacks on takedowns: group up and finish low targets', '死了也有效果：残局敢拼': 'Works even when you die: take the fight', '残血才触发：别太早撤，残血再拼一下': "Triggers at low HP: don't back off too early", '对队友放治疗 / 护盾才有效': 'Only works when you heal/shield allies', '围绕大绝：大绝好了再开团': "Built around your ult: fight when it's up", '持续伤害：先挂上伤害再拉开': 'Damage over time: apply it, then kite', '靠普攻触发：技能空档多 A': 'Triggered by attacks: auto between abilities', '靠技能命中：多放技能消耗': 'Triggered by ability hits: poke with abilities', '拿了就生效，不用特别操作': 'Works automatically, nothing special to do', '残血或被集火时按：2.5 秒无敌，等对面技能落空': 'Press when low or focused: 2.5s invulnerable, wait out their spells', '残血时按：2.5 秒无敌（只能用一次）': 'Press when low: 2.5s invulnerable (one use)', '被晕、被定住时马上按：解控': 'Press right after being stunned/rooted: cleanse', '团战时对准人多处按：全队回血、对敌人造成伤害': 'Press on the crowd in fights: heals allies, damages enemies', '队友被控时对他按：解控加回血': "Press on a CC'd ally: cleanse and heal", '开团或被开时按：全队护盾': 'Press when a fight starts: team shield', '普攻后马上按：重置普攻、范围伤害': 'Press right after an auto: reset and AoE', '普攻后马上按：重置普攻、多打一下': 'Press right after an auto: attack reset', '贴脸按：范围伤害': 'Press up close: AoE damage', '开团或追人前按：大幅加速': 'Press before engaging or chasing: big speed', '按了往前冲：开团或追残血': 'Press to dash forward: engage or chase', '贴近敌人按：伤害加缓速，追人用': 'Press near enemies: damage and slow, for chasing', '开团或撤退时按：全队加速': 'Press when engaging or retreating: team speed', '按了往前扔：缓速再禁锢': 'Press to throw forward: slow then root', '有主动效果：记得按': 'Has an active: remember to press it', '残血 → 按 {0} {1}': 'Low HP → press {0} {1}', '血量低于 30% → 按 {0} {1}，等技能落空': 'Below 30% HP → press {0} {1}, wait out their spells', '★ {0} 怎么用：{1}': '★ How to use {0}: {1}', '【怎么打出效果】': '[How to get the effect]', '按 {0} {1}：{2}': 'Key {0} {1}: {2}', '「{0}」：{1}': '[{0}]: {1}', '带着{0}阵亡 {1} 次：残血先按 {2}，等对面技能落空再走': 'Died {1}× holding {0}: press {2} when low, wait out their spells', '下局练习：': 'Practice next game: '})
EN.update({'能处决低血敌人：优先打残血的': 'Executes low-HP enemies: focus low targets'})
EN.update({'练习模式': 'Practice mode', '练习模式…': 'Practice mode…', '练习完成': 'Practice done', '答对 {0}/{1}': '{0}/{1} correct', '题库：{0} 题要复习（答错的会马上再出，答对的隔 1、3、7、21 天再考），已学会 {1} 题': 'Deck: {0} cards to review (wrong ones come back right away, right ones after 1/3/7/21 days); {1} learned', '再练一次残血按键反应': 'Practice the low-HP key reaction again', '关闭': 'Close', '练习 {0}/{1}': 'Practice {0}/{1}', '新题': 'new', '复习': 'review', '{0} · 第 {1} 分钟的三选一：哪张最好？': '{0} · augment pick at {1} min: which is best?', '{0} · 第 {1} 分钟，你身上有 {2}。下一件买什么？': '{0} · at {1} min you have {2}. What next?', '（还没有成品装）': '(no completed items yet)', '✓ 答对了': '✓ Correct', '✗ 推荐是「{0}」': '✗ The pick is [{0}]', '不在当时推荐的前 3 名': 'not in the top 3 at the time', '（你当时选的）': ' (your choice)', '怎么用：': 'How to use: ', '下一题 →': 'Next →', '反应练习：残血按 {0} {1}': 'Reaction drill: press {0} {1} when low', '血条掉到红线（30%）以下时，马上按键盘 {0}。太早按算浪费，掉到 0 算阵亡。共 5 次。': 'When the bar drops below the red line (30%), press {0} immediately. Too early wastes it, reaching 0 means death. 5 rounds.', '准备…': 'Get ready…', '✗ 阵亡了：掉到红线就要按': '✗ Dead: press as soon as it crosses the line', '✗ 太早了：还没到残血，中娅浪费了': '✗ Too early: not low yet, wasted', '✓ {0:.2f} 秒': '✓ {0:.2f}s', '{0}/5 成功，平均反应 {1:.2f} 秒': '{0}/5 success, avg reaction {1:.2f}s', '✓ 过关': '✓ Passed', '再练一次': 'Try again', '再来一次': 'Again', '第 {0}/5 次': 'Round {0}/5', '现在没有要练的题。打完一局，失误（没选 ★ 的增幅、不在推荐里的装备、带着中娅阵亡）会自动变成题目。': 'Nothing to practice yet. After a game, mistakes (augment not ★, item not recommended, dying with Zhonya) become cards automatically.', '先练残血按键反应': 'Practice the low-HP key reaction', '这局的失误变成了 {0} 道练习题：点这里或 ⋯ → 练习模式': "This game's mistakes became {0} practice cards: click here or ⋯ → Practice mode", '中娅沙漏': "Zhonya's Hourglass"})
EN.update({'分给你的': 'offered to you', '备选席': 'bench', '★ 推荐 {0}（{1}）': '★ Pick {0} ({1})'})
EN.update({'{0}（{1}）{2}/{3}/{4}，参团率 {5:.0f}%': '{0} ({1}) {2}/{3}/{4}, kill participation {5:.0f}%', '对手': 'enemy', '出装：': 'Build: ', '强势期：第 {0} 分钟出了{1}之后，5 分钟内拿了 {2} 个人头': 'Power spike: after {1} at {0} min, {2} kills within 5 min', '死得少：每 10 分钟死 {0:.1f} 次（你 {1:.1f} 次）— 活着才能输出': 'Dies less: {0:.1f} deaths per 10 min (you {1:.1f}) — you can only deal damage alive', '他杀了你 {0} 次：他出了{1}之后要避开正面': 'Killed you {0}×: avoid fighting him head-on after {1}', '核心装': 'core item', '本局最强：': 'MVP: ', '向高手学：这局最强的是{0}（{1}）。他第 {2} 件成品（第 {3} 分钟）出了什么？': 'Learn from the best: the MVP was {0} ({1}). What was his item #{2} (at {3} min)?', '✗ 他出的是「{0}」': '✗ He built [{0}]'})
EN.update({'和你同定位：': 'Same role as you: ', '值得学：': 'Worth learning from: '})
EN.update({'净贡献：每 10 分钟 {0:+.1f} 个人头（你 {1:+.1f}）': 'Net contribution: {0:+.1f} kills per 10 min (you {1:+.1f})'})
EN.update({'杀了你 {0} 次：出了{1}之后要避开正面': 'Killed you {0}×: avoid fighting head-on after {1}', '向高手学：这局最强的是{0}（{1}）。{0}第 {2} 件成品（第 {3} 分钟）出了什么？': 'Learn from the best: the MVP was {0} ({1}). What was {0}\'s item #{2} (at {3} min)?', '✗ 出的是「{0}」': '✗ It was [{0}]'})
EN.update({'承伤': 'tanked', '占全队：': 'Share of team: ', '（你 {0:.0f}%）': ' (you {0:.0f}%)', ' · 已用结算数据更新': ' · updated with end-of-game stats', '高手出装（{0} 局里当过最强）：{1}': 'Pro build (MVP in {0} games): {1}'})
EN.update({'比队友多赚：每 10 分钟 {0:+.1f} 个人头（你 {1:+.1f}）': 'Above teammates: {0:+.1f} kills per 10 min (you {1:+.1f})', '复盘出错：{0}': 'Review error: {0}'})
EN.update({'伤害输出': 'damage'})
EN.update({'{0:.1f} 万局': '{0:.1f}0k games', '{0} 局': '{0} games', '{0} {1:+.1f}%（±{2:.1f}），{3}': '{0} {1:+.1f}% (±{2:.1f}), {3}', '；{0} {1:+.1f}%': '; {0} {1:+.1f}%', '第 {0} 件出它': 'as item #{0}', '整局出它': 'built at all', '带「{0}」时': 'with [{0}]', '这个英雄几乎没人出（没数据）': 'almost nobody builds this on this champion (no data)', '网上数据还没载入': 'online data not loaded yet', '第 {0} 次选它': 'as pick #{0}', '拿它': 'taking it', '和「{0}」一起': 'together with [{0}]', '没有这个英雄的数据': 'no data for this champion', '已选增幅改变了出装，平时的数据不适用': "your augments change the build; usual data doesn't apply", '网上数据：': 'Online data: ', '本局调整 {0:+.1f}%：': 'This-game adjustment {0:+.1f}%: ', '出这双鞋': 'these boots', '这个英雄几乎没人买（没数据）': 'almost nobody buys these on this champion (no data)', '没数据': 'no data', '数据 {0:+.1f}': 'data {0:+.1f}', '本局 {0:+.1f}：': 'game {0:+.1f}: ', ' {0}. {1:<10} {2:>5}%  [{3}｜本局 {4:+.1f}] {5}': ' {0}. {1:<20} {2:>5}%  [{3} | game {4:+.1f}] {5}', ' {0}. {1:<10} {2:>5}%  [{3}｜本局 {4:+.1f}] {5}{6}': ' {0}. {1:<20} {2:>5}%  [{3} | game {4:+.1f}] {5}{6}', '★ 选 {0}（{1}%）': '★ Pick {0} ({1}%)'})
EN.update({'数据载入中': 'loading data'})
EN.update({
    "——": " — ",
    "Riot 查不到你的对局：检查服务器和 Riot ID 是否正确": "Riot returned none of your games: check the server and Riot ID",
    "自建数据库：看了 {0} 局都不是海斗（{1}），打一局海斗后再试": "Own database: checked {0} games, none were Mayhem ({1}); try again after a Mayhem game",
    "自建数据库：对局中，暂停收集": "Own database: paused while in game",
    "{0} · {1}。这一段最主要的问题是？": "{0} · {1}. What was the main problem here?",
    "{0} 胜率 {1}% → {2}%（我方阵亡 {3}，敌方阵亡 {4}）": "{0} win chance {1}% → {2}% (ally deaths {3}, enemy deaths {4})",
    "人数不利还接团": "Took a fight while outnumbered",
    "关键时刻：": "Key moment: ",
    "团战前你第一个阵亡，队伍马上少一个人。站在前排后面半个身位，等对面关键技能交了再进。":
        "You died first, so your team fought a man down. Stand half a step behind your frontline and go in after their key spells are used.",
    "团战换人吃亏": "Lost the trade in the teamfight",
    "实时胜率模型：{0} 局训练，第 8 分钟后准确率 {1:.0f}%": "Live win model: trained on {0} games, {1:.0f}% accurate after minute 8",
    "实时胜率模型：时间线 {0}/{1} 局（攒够就自动训练）": "Live win model: timelines {0}/{1} games (trains automatically when enough)",
    "对面关键装备做出来了、经济追上。这时别正面硬打，等自己下一件再接团。":
        "Their key items came online and they caught up in gold. Don't force head-on fights; wait for your next item.",
    "对面装备成型，我们还在硬打": "Kept forcing fights after their items spiked",
    "我先倒下（站太前 / 先手被抓）": "I died first (too far forward / got caught)",
    "✗ 答案是「{0}」": "✗ The answer is [{0}]",
    "最好的一波：": "Best play: ",
    "没人阵亡但被推塔：兵线没处理。清完兵再找机会，不要在塔前空站。":
        "Lost a tower with no deaths: the wave wasn't handled. Clear the wave first; don't idle in front of the tower.",
    "没打架却丢了塔": "Lost a tower without a fight",
    "界面出错（已记录 ui_error.log）": "UI error (logged to ui_error.log)",
    "胜率": "Win%",
    "胜率 {0}%": "Win {0}%",
    "胜率模型已更新：{0} 局，第 8 分钟后准确率 {1:.0f}%": "Win model updated: {0} games, {1:.0f}% accurate after minute 8",
    "这段时间稳稳推进、经济拉开": "Steady pushing pulled ahead in gold",
    "这波团战换输了。先打离你最近、最脆的目标，别追残血追到敌方后排。":
        "You lost that teamfight trade. Hit the closest squishy target; don't chase low-HP enemies into their backline.",
    "这波打得好：{0} 换 {1}": "Great fight: {0} for {1}",
    "队友还没复活就开打。少人时退回塔下拖时间，等人齐再打。":
        "Fought before teammates respawned. When down a player, fall back under tower and wait for the team.",
    "｜网上胜率 {0:.1f}%": " | online win rate {0:.1f}%",
    "每局也会抓时间线，攒够 150 局后自动训练实时胜率。": " It also fetches each game's timeline and trains the live win model after 150 games.",
})

COMBOS_EN = {'Aatrox': {'notes': ['Use E to adjust so all three Q casts land with the sweet spot (outer edge)',
                      'R for speed to stick to targets; heals more the lower you get'],
            'style': "Frontline fighter: go in after they burn CC, don't back off with R up"},
 'Ahri': {'notes': ['Land E charm, then Q out and back + W; R to chase or dodge',
                    'R to close the gap first, then E hits far more often'],
          'style': 'Only go in after E lands; save one R dash to escape'},
 'Akali': {'notes': ['Q procs passive ring, E mark then recast E to dash, R twice to secure kills',
                     'W shroud restores energy and dodges turret shots and skills'],
           'style': "Go in after their CC is down; don't dive without W"},
 'Akshan': {'notes': ['Auto constantly while swinging on E, Q on landing',
                      'Fully charge R to execute low-HP targets'],
            'style': 'Poke from the edge; kill the scoundrel who killed an ally to revive them'},
 'Alistar': {'notes': ['Q right after W connects: classic headbutt-pound',
                       'Flash Q for AoE knock-up, then W the carry toward your team'],
             'style': 'Engage support: have R ready before going in, R to reduce damage when focused'},
 'Ambessa': {'notes': ['Both Q casts, E spin into W block, R to pull and suppress',
                       'Every ability grants a dash; weave autos between spells'],
             'style': "Melee fighter: R onto the backline, don't get kited outside"},
 'Amumu': {'notes': ['Land Q, then R for AoE root; keep W on', 'Flash R to engage when grouped'],
           'style': 'Engage tank: Q has two charges, keep the second if the first misses'},
 'Anivia': {'notes': ['E deals double damage after Q detonates and chills',
                      'W wall to split or block enemies, then follow with Q'],
            'style': 'Mid-range mage: R in the crowd for zone control; protect your egg'},
 'Annie': {'notes': ['At 4 passive stacks, R stuns on summon', 'Passive ready: Flash R for an instant engage'],
           'style': 'Build passive stun before committing; E shield self or frontline'},
 'Aphelios': {'notes': ['Time R to your current guns; moonlight burst marks every enemy',
                        'Crimson/Gravitum to pressure, Calibrum to clear from range'],
              'style': 'Know your gun combo; swap to the best offhand after R'},
 'Ashe': {'notes': ['R arrow stun, W slow, then Q volley', 'E hawkshot to scout brush for ambushes'],
          'style': 'Ranged slow kiter; R can engage from very far'},
 'AurelionSol': {'notes': ['W fly for angles, Q breath for sustained damage, E black hole pulls',
                           'E pulls them to the center, then R to knock up'],
                 'style': 'Scales hard; clean up with long-range breath'},
 'Aurora': {'notes': ['Q out and recall it, E knockback to keep distance, R traps an area',
                      'W invisibility to go in and out'],
            'style': 'Hit and run; keep dealing damage inside R'},
 'Azir': {'notes': ['Place soldiers, Q them forward, soldier autos for damage',
                    'Soldier dash + Q, then R to push enemies into your team'],
          'style': 'Fight from the back with soldiers; R to peel or counter-engage'},
 'Bard': {'notes': ['Q only stuns if a wall or second enemy is behind the target',
                    'R stasis an area; can freeze allies to save them'],
          'style': "Roaming support: careful with R, don't freeze your own carry"},
 'Belveth': {'notes': ['Q dashes in four directions to close in, E to flurry in place', 'W knock-up into Q'],
             'style': 'Eat enemy corpses for true form; attack faster after R'},
 'Blitzcrank': {'notes': ['After Q hook, E knock-up, R to interrupt and silence',
                          'R first to strip shields, then hook'],
                'style': 'Hooking their backline wins fights; missed hook means back off'},
 'Brand': {'notes': ['Q always stuns after E ignites', 'R bounces and explodes in crowds'],
           'style': 'Passive detonates at 3 stacks; top-tier Mayhem poke'},
 'Braum': {'notes': ['Q slow, then autos to 4 stacks for stun', 'E shield blocks projectiles for the backline'],
           'style': 'Stand in front of allies to block skills; R knock-up to engage or counter'},
 'Briar': {'notes': ['W frenzy dash into nonstop autos, Q stun', 'R locks onto a distant target and charges'],
           'style': 'Stronger the lower you are; E to heal and disengage after a fight'},
 'Caitlyn': {'notes': ['E net hit, then trap for headshot damage', 'R to finish low-HP targets'],
             'style': 'Very long-range poke; traps block escape paths'},
 'Camille': {'notes': ['E wall hook, recast E to stun, W outer edge slows, two Q casts', 'R traps a single carry'],
             'style': 'Duelist: R the backline and fight them inside'},
 'Cassiopeia': {'notes': ['Spam E once Q poisons', 'R from the front to petrify, W grounds dashes'],
                'style': 'Close-range sustained damage; no boots (passive)'},
 'Chogath': {'notes': ['Q knock-up into W silence, R to execute', 'Every R kill grows you and adds HP'],
             'style': 'Stack R to get tankier; R one-shots low-HP targets'},
 'Corki': {'notes': ['W in dropping fire, E flamethrower, Q bomb', 'Keep firing R missiles to poke'],
           'style': 'Long-range missile poke; Package W to dive and clean up'},
 'Darius': {'notes': ['E pull, auto, W reset, then Q outer edge',
                      'At 5 Hemorrhage stacks R executes; kills reset it'],
            'style': 'Go in at full stacks, chain R executes'},
 'Diana': {'notes': ['Q mark then R to knock up, E dashes both ways', 'Land Q, E in, follow with R'],
           'style': 'Assassin/fighter: R pulls for AoE knock-up'},
 'DrMundo': {'notes': ['Q cleaver from range, E empowered auto', 'Nearly unkillable with R up'],
             'style': "Be the frontline once R is up; don't fear focus"},
 'Draven': {'notes': ['Catch axes for nonstop autos, E knockback', 'R hits twice to secure kills'],
            'style': "Catch axes to snowball; drop them if you're getting caught"},
 'Ekko': {'notes': ['E dash empowers auto, combo with W stun zone', 'R rewinds 4 seconds, heals and explodes'],
          'style': 'Assassin: predict movement with W, R back when low'},
 'Elise': {'notes': ['Human E cocoon, Q W, then spider form to keep hitting', 'Spider E rappel dodges skills'],
           'style': 'Burst if cocoon lands; back off if it misses'},
 'Evelynn': {'notes': ['W charm, then Q E, R execute and blink out', 'R works as an escape dash'],
             'style': 'Stealth hunt isolated targets; easy to get caught in Mayhem, wait for fights to dive'},
 'Ezreal': {'notes': ["W mark then Q to pop, E blink and keep Q'ing", 'R global poke or to finish low-HP targets'],
            'style': 'Spam Q to poke; save E for escape'},
 'Fiddlesticks': {'notes': ['E silence, Q fear, R into the crowd, W drain',
                            'Hide during R channel; Flash R to engage'],
                  'style': 'Engage mage: hide on the flank, R into the middle of them'},
 'Fiora': {'notes': ['Hit Vital with Q, auto, E reset', 'W parries CC and stuns back'],
           'style': 'Dueling queen: W key CC, hit all R vitals for team healing'},
 'Fizz': {'notes': ['Q through a target then W, E hop to dodge skills', 'Full combo after R shark lands'],
          'style': 'E dodges key skills, R to open'},
 'Galio': {'notes': ['Q poke, E charge to knock up, W taunt', 'R flies to an ally to help'],
           'style': 'AP tank: W taunts a group, R to save a dived ally'},
 'Gangplank': {'notes': ['Set barrels, Q a barrel to chain explosions', 'W cleanses CC and heals'],
               'style': 'Chain barrel explosions; R for global support'},
 'Garen': {'notes': ['Q silence, E spin, R execute', 'W to reduce damage and tank'],
           'style': 'Simple: Q in their face, R to execute their carry'},
 'Gnar': {'notes': ['Mini form: stack W 3 rings, Q boomerang', 'Mega form: E into the crowd, R into walls to stun'],
          'style': 'Kite as Mini Gnar; join fights when about to transform'},
 'Gragas': {'notes': ['E body slam then Q barrel, R knocks them into your team', 'Flash E for a surprise engage'],
            'style': 'R their carry into your team'},
 'Graves': {'notes': ['E dash resets auto, Q bounces off walls', 'W smoke blinds, then R for damage'],
            'style': 'Close-range burst; E stacks armor'},
 'Gwen': {'notes': ['E dash, autos to stack Q snips, hit Q center',
                    "W can't be targeted from outside; R three casts"],
          'style': 'Melee sustained damage; W blocks ranged damage'},
 'Hecarim': {'notes': ['E charge knocks back, R into crowd to fear', 'Heal from W while active'],
             'style': 'Charge to engage; knock enemies into your team'},
 'Heimerdinger': {'notes': ['Place turrets, E stun then W rockets', 'R upgrade turret to hold a zone'],
                  'style': 'Zone and poke; in Mayhem stand by your turrets'},
 'Hwei': {'notes': ['E-series CC (EQ fear / EE pull) into Q-series burst', 'R spreads through crowds'],
          'style': 'Many combos; CC first, then burst'},
 'Illaoi': {'notes': ['E pull out spirit and hit it, W slam tentacles',
                      'R fills the area with tentacles when grouped'],
            'style': 'In big Mayhem fights, R in the middle'},
 'Irelia': {'notes': ['E both blades to stun, then Q marked targets', 'R marks everyone; Q resets through the crowd'],
            'style': 'Go in at full passive stacks, chain Q resets'},
 'Ivern': {'notes': ['Q root then jump to target, E shield', 'R summons Daisy to join'],
           'style': 'Support: shield your carry, Q to pull allies in'},
 'Janna': {'notes': ['Q knock-up, R knocks back enemies and heals', "E shield ally who's dealing damage"],
           'style': 'Peel support: R knocks back divers'},
 'JarvanIV': {'notes': ['EQ knock-up, then R to trap', 'Flash EQ for a surprise engage'],
              'style': 'EQ to engage, R to trap the carry'},
 'Jax': {'notes': ['Q jump in, E counter to stun, W empowered auto', 'Q can jump to allies/wards'],
         'style': 'E dodges autos; R makes you tankier as you fight'},
 'Jayce': {'notes': ['Cannon Q through gate for huge damage', 'Hammer: jump in, W for attack speed, E knockback'],
           'style': 'Poke with gated cannon; hammer to finish low-HP targets'},
 'Jhin': {'notes': ['W roots from range after hitting a marked target', 'R fires 4 shots; the last always crits'],
          'style': 'Four-shot rhythm; the 4th hurts most'},
 'Jinx': {'notes': ['W slow, then swap to Fishbones rockets for teamfights',
                    'R cleans up from range; kills trigger passive speed'],
          'style': 'Hide behind frontline; go wild once a takedown procs passive'},
 'KSante': {'notes': ['Third Q knocks up, W charges', 'R kicks target away, enters all-out mode'],
            'style': 'Tank early, deal damage after R'},
 'Kaisa': {'notes': ['Q hits hardest near isolated targets, W procs passive', 'R dashes to a marked enemy'],
           'style': 'Stack passive marks before R-ing in'},
 'Kalista': {'notes': ['Hop-auto to stack spears, E rend; kills reset E',
                       'R throws bound ally into crowd for knock-up engage'],
             'style': 'Kite with hops; E low-HP targets for resets'},
 'Karma': {'notes': ['R-empowered Q for burst', 'R-empowered E shields and speeds the whole team'],
           'style': 'Great Mayhem poke/support; R comes back fast'},
 'Karthus': {'notes': ['Keep tapping Q on targets, E for sustained damage', 'Global R wipes low-HP enemies'],
             'style': 'Keep dealing damage in passive after death; R cleans up everyone low'},
 'Kassadin': {'notes': ['R blink in, full combo', 'More R stacks, more damage'],
              'style': 'Unstoppable mid-late; R onto isolated backliners'},
 'Katarina': {'notes': ['E to daggers procs passive; kills reset E', 'R spin in the crowd'],
              'style': 'Clean up in fights; one kill starts the chain'},
 'Kayle': {'notes': ['Q slows and shreds resists, E empowered auto executes',
                     'R makes self or ally invulnerable and calls judgment'],
           'style': 'Scales hard; R the ally being focused'},
 'Kayn': {'notes': ['Shadow Assassin dives through walls, Rhaast lifesteals', 'R into an enemy to dodge skills'],
          'style': 'Red Kayn frontline, blue Kayn assassin'},
 'Kennen': {'notes': ['E into the crowd, R to 3 stacks for stun', 'Flash R for a huge engage'],
            'style': 'Stack R to stun a whole group at once'},
 'Khazix': {'notes': ['E jump in, Q deals double to isolated targets', 'R stealth in and out'],
            'style': 'Hunt isolated targets; evolve Q first'},
 'Kindred': {'notes': ['Q dash, W wolf for sustained damage, E executes on 3rd hit',
                       'R keeps everyone in the zone from dying'],
             'style': 'R to save allies or bait enemies'},
 'Kled': {'notes': ['Q pull then E in, R charge speeds up team', 'E recast to chase'],
          'style': 'Engage mounted; regain courage when dismounted'},
 'KogMaw': {'notes': ['W for long-range autos + % damage, Q shreds resists, E slows',
                      'R long-range artillery, more damage vs low HP'],
            'style': 'Stand behind frontline with W on; needs peel'},
 'Leblanc': {'notes': ['Q mark, W in, E chain, R mimics a skill', 'W recast returns to start'],
             'style': 'Burst one-shot, then W back'},
 'LeeSin': {'notes': ['Land Q, recast to fly in, R kick', 'Ward/Flash behind, R kick them back'],
            'style': 'Go in when Q lands; R kick the carry'},
 'Leona': {'notes': ['E dash in, Q stun, R AoE stun', 'R stun from range, then dash in'],
           'style': 'Engage tank; chain stuns'},
 'Lillia': {'notes': ['E seed slows, Q edge deals true damage and speed, W center hits hard',
                      'Any damage applies passive; R sleeps all marked enemies'],
            'style': "Run around the fight's edge, stack Q speed, R to sleep a group"},
 'Lissandra': {'notes': ['E claw through, R freezes target', 'R on self for invulnerability'],
               'style': 'Engage or counter-engage; self-R to survive'},
 'Lucian': {'notes': ['E dash resets auto; double shot after every ability', 'R to spray'],
            'style': 'Weave autos between skills for short burst'},
 'Lulu': {'notes': ['W speed and attack speed on your carry, or polymorph an assassin',
                    'R enlarges a focused ally and knocks up nearby'],
          'style': 'Protect your carry; W polymorph to stop assassins'},
 'Lux': {'notes': ['Q root, E slow, R laser', 'W shield for the frontline'],
         'style': 'Long-range poke; Q hit means full combo'},
 'Malphite': {'notes': ['R into the crowd for knock-up, E cuts attack speed', 'Flash R to engage'],
              'style': 'R to engage and dive the backline'},
 'Malzahar': {'notes': ['W voidlings, E damage over time, R suppress', 'R suppress the carry'],
              'style': 'Suppress their core; voidlings are strong in Mayhem'},
 'Maokai': {'notes': ['W root into Q knockback, R roots', 'E saplings in brush'],
            'style': 'Mayhem tank: R limits enemy movement'},
 'MasterYi': {'notes': ['Q dodges skills, E true damage, R speed', 'W heals and reduces damage'],
              'style': 'Wait for their CC, then Q in'},
 'Mel': {'notes': ['E root then Q barrage, W reflects projectiles', 'R detonates passive marks to execute'],
         'style': 'W to reflect skills, R to clean up'},
 'Milio': {'notes': ['W extends range and heals, E shield and speed', 'R cleanses team CC'],
           'style': "Boost your carry's range; R cleanse saves fights"},
 'MissFortune': {'notes': ['E slow, then R Bullet Time', 'Q bounces to hit the target behind'],
                 'style': 'R strafes crowds; Mayhem AoE queen'},
 'MonkeyKing': {'notes': ['E dash, Q to interrupt, R spin knock-up', 'W clone baits skills'],
                'style': 'R spins to knock up a group'},
 'Mordekaiser': {'notes': ['E pulls in; Q hits hardest on a lone target; W shield converts to healing',
                           'R drags the carry into the Death Realm 1v1; win to steal stats'],
                 'style': 'R the enemy carry into a 1v1'},
 'Morgana': {'notes': ['Q root, then W pool; R chain stun', 'E Black Shield blocks CC'],
             'style': 'E shield allies getting engaged on'},
 'Naafiri': {'notes': ['R to hunt (MS, shield), W dash to target, E dash and recall pack, Q bleed',
                       'Hit the same target with both Q casts for bonus damage'],
             'style': 'Assassin: more dogs = more damage, dive low-HP backline'},
 'Nami': {'notes': ['Q bubble stun, E empowers ally autos', 'R wave knocks up a line'],
          'style': 'Q bubble to set up ally damage, R to engage'},
 'Nasus': {'notes': ['Q stacks permanently on minions/champs; fast in Mayhem with many minions',
                     'W Wither slows hard; E shreds armor, then Q'],
           'style': 'Focus Q stacks early; after R, frontline and W the carry'},
 'Nautilus': {'notes': ['Q hook, then auto to root; R Depth Charge', 'W shield'],
              'style': 'Q hook, R is guaranteed CC'},
 'Neeko': {'notes': ['E root grows stronger through multiple targets; R leap for AoE stun',
                     'W clone baits skills; disguise as ally, walk in, R'],
           'style': 'Disguise as an ally to get close, R big teamfights'},
 'Nidalee': {'notes': ['Human Q spear hits harder at range and marks',
                       'Cougar W jumps farther to marked targets, E swipe, Q execute'],
             'style': 'Poke with spears, then Cougar to finish marked targets'},
 'Nilah': {'notes': ['E dash in, R pulls a group', 'W dodges autos'],
           'style': 'Close-range AoE damage, strong in Mayhem fights'},
 'Nocturne': {'notes': ['R blinds enemy team and flies to target; Q MS; E tether into fear',
                        'W shield blocks a spell and grants AS'],
              'style': 'R Paranoia onto backline, E fear'},
 'Nunu': {'notes': ['W snowball knocks up; E 3 hits roots, then R',
                    'Fully channel R; charge as long as possible before interrupt'],
          'style': 'W snowball from the side to engage, R after CC lands'},
 'Olaf': {'notes': ['Q axe slows; pick it up to reset Q; E true damage',
                    'CC immune during R; charge in and hit the carry'],
          'style': 'R and dive in, ignore CC'},
 'Orianna': {'notes': ['Q ball into the group, W slow, R pulls', 'E ball onto diving ally, then R'],
             'style': 'Ball on the engaging ally, R to pull a group'},
 'Ornn': {'notes': ['Q raises a pillar; E into it for a knock-up',
                    'R summons the ram; recast R to redirect it for a knock-up'],
          'style': 'Engage tank, long-range R knocks up a line'},
 'Pantheon': {'notes': ['W stun then Q poke, E blocks', 'R drops in to support'], 'style': 'W stun into Q burst'},
 'Poppy': {'notes': ['E pins into walls to stun, Q damage', 'Charge R to launch far, or tap to knock up'],
           'style': 'E into walls; W stops dashes'},
 'Pyke': {'notes': ['Q pull, E phantom stuns on pass-through, R execute', 'W camo + MS to approach, then E stun'],
          'style': 'R can chain resets; kill gold shared with ally'},
 'Qiyana': {'notes': ['W grab element, E dash in, R into walls', 'R shockwave stuns a group against walls'],
            'style': 'Fight near walls to R into them'},
 'Quinn': {'notes': ['Q blinds; auto to pop passive mark; E vault re-marks', 'R to fly with MS to escape or chase'],
           'style': 'Ranged kiting; E interrupts dashes'},
 'Rakan': {'notes': ['W jump in to knock up, R charms along path, E back to ally',
                     'R first, run in, then W; harder to dodge'],
           'style': 'Engage support: E to ally for entry and exit'},
 'Rammus': {'notes': ['Q roll in to knock back, E taunt, W thorns', 'R leap and land knock-up, then Q to chase'],
            'style': 'Hard counter to AD autoattackers; taunt the ADC'},
 'RekSai': {'notes': ['Burrowed E tunnel to close in, W unburrow knock-up, Q empowered autos',
                      'R executes marked low-HP targets'],
            'style': 'Kite with tunnels; unburrow on backline'},
 'Rell': {'notes': ['W dismount slam knock-up, E tether stun with ally, R pulls nearby in',
                    'Flash W for surprise knock-up'],
          'style': 'Engage tank: R to group enemies for AoE'},
 'Renata': {'notes': ['Q grab, then recast to throw into other enemies', 'R makes enemies attack their allies'],
            'style': 'R on clumped enemies, W saves dying allies'},
 'Renekton': {'notes': ['E in, empowered W stun, Q heal, E2 out', 'R for size and HP; use before fights'],
              'style': 'Go in at 50 Fury; empowered skills are key'},
 'Rengar': {'notes': ['R stealth in and leap, empowered E root', 'Passive leap only from brush/stealth'],
            'style': 'Few bushes in Mayhem, rely on R for angles'},
 'Riven': {'notes': ['E shield gap close, R for blade, weave Q with autos, W stun', 'R2 wind slash executes low HP'],
           'style': 'Weave Q with autos to cancel, E to absorb damage'},
 'Rumble': {'notes': ['E harpoon slows, Q flamethrower, R fire zone', 'Empowered at 50+ Heat; avoid overheat'],
            'style': 'Lay R sideways across enemy pathing'},
 'Ryze': {'notes': ['E spreads flux, W root, Q resets for chains', 'R teleports team to engage/escape'],
          'style': 'Combo E-Q-W-Q; stronger with more mana'},
 'Samira': {'notes': ['E in to build Style; Q/A to keep stacking; R at S rank', 'W spin blocks projectiles'],
            'style': 'Let someone engage first, then E in'},
 'Sejuani': {'notes': ['Q charge knock-up; E stun at full Frost; R big freeze',
                       'Land long-range R on carry, then dive'],
             'style': 'Engage tank, R has huge range'},
 'Senna': {'notes': ['W root then piercing Q, also heals allies', 'Global R: damages enemies, shields allies'],
           'style': 'Long-range damage/support; more souls, more range'},
 'Seraphine': {'notes': ['Every third spell echoes; E slow, hit again to root',
                         'R extends through allies, charms a line'],
               'style': 'Stay back and sing; cast R through allies'},
 'Sett': {'notes': ['E stuns only with enemies on both sides; full W true damage in center',
                    'R throws frontliner into backline, then E'],
          'style': 'Tank to charge W; R the tank into the group'},
 'Shaco': {'notes': ['Box first for fear, Q stealth backstab, E slow', 'R clone baits skills, explodes on death'],
           'style': 'Mayhem: pre-place boxes at chokepoints'},
 'Shen': {'notes': ['E dash taunt, Q pulls blade, W blocks autos', 'R shields a focused ally and teleports to them'],
          'style': 'Engage and peel; global R to protect carry'},
 'Shyvana': {'notes': ['E fireball mark, W burn, Q two autos', 'Dragon R dash in; E leaves a fire zone'],
             'style': 'Build full Fury, dragon form, then fight'},
 'Singed': {'notes': ['Run up with poison trail, E flip behind you', 'W glue blocks dashes, then flip'],
            'style': 'Weave through the group with Q on'},
 'Sion': {'notes': ['E shreds armor, full-charge Q knock-up', 'Long-range R charge into walls/enemies'],
          'style': 'R from far into groups; passive fights after death'},
 'Sivir': {'notes': ['Q boomerang out and back, W ricochet waveclear', 'E shield blocks key CC'],
           'style': 'E spell shield; R team MS to chase/escape'},
 'Skarner': {'notes': ['E grab into wall stun; R suppresses up to 3; W shield slow', 'Q rock throw for ranged slow'],
             'style': 'E into walls, R drags the carry back'},
 'Smolder': {'notes': ['Q hits/kills build stacks; W sneeze slows',
                       'E fly over walls to reposition; R hits yourself to heal'],
             'style': 'Stack safely early, scales hard'},
 'Sona': {'notes': ['Q damage empowers autos, E team MS', 'R line AoE stun'],
          'style': 'Auras for team, R to engage or counter-engage'},
 'Soraka': {'notes': ['Q hits for heal and MS, then W allies', 'E silence zone, roots at edge'],
            'style': 'Heal from range, global R to save'},
 'Swain': {'notes': ['W long-range vision/slow, E pull root, Q close burst', 'R drain DoT; R2 for burst'],
           'style': 'Frontline mage: R on in the group to drain'},
 'Sylas': {'notes': ['E dash, E2 chain, Q cross, W heal/execute', 'R steals the best enemy ult'],
           'style': 'Stealing an engage ult (Malphite, Leona) is huge'},
 'Syndra': {'notes': ['Q sphere then E push to stun', 'W throw slows; R with all spheres to execute'],
            'style': 'More spheres = stronger R; QE stun then R'},
 'TahmKench': {'notes': ['Q stuns at 3 passive stacks', 'R devours ally to save, or enemy at 3 stacks'],
               'style': 'R to save focused ally and carry them'},
 'Taliyah': {'notes': ['E lays rock mines, W knocks enemies into them', 'Q rapid stone volley'],
             'style': 'R wall splits enemies or rotates fast'},
 'Talon': {'notes': ['W blades, E vaults walls, Q leap, R stealth', 'R stealth then Q in for melee crit'],
           'style': 'Assassin: full combo, R stealth out'},
 'Taric': {'notes': ['W link ally, E stuns from both', 'R: team invulnerable 2.5s after delay'],
           'style': 'Link the engaging ally, R to save team'},
 'Teemo': {'notes': ['Q blinds ADCs/fighters, autos stack poison', 'R shrooms on enemy pathing'],
           'style': 'Carpet Mayhem with shrooms, poke from back'},
 'Thresh': {'notes': ['Q hook, recast to fly in, E knock-up', 'W lantern pulls allies back'],
            'style': 'Land hook and go; lantern saves'},
 'Tristana': {'notes': ['E bomb detonates at 4 stacks, W jump in to clean up', 'R knocks back divers'],
              'style': 'W resets on kills; hop to clean up'},
 'Trundle': {'notes': ['Q steals AD, E pillar splits enemies', 'R steals tank resists and HP'],
             'style': 'R the fattest enemy tank'},
 'Tryndamere': {'notes': ['E spin in, crits build Fury, Q heal', 'R: 5s undying, Q to heal before it ends'],
                'style': 'Go all out during R, Q as it ends'},
 'TwistedFate': {'notes': ['W Gold Card stun, then Q guaranteed', 'Red Card AoE slow waveclear'],
                 'style': 'Gold Card for team follow-up, Q poke'},
 'Twitch': {'notes': ['Q stealth to flank, autos stack poison, E detonate', 'R autos pierce a line'],
            'style': 'Stealth for flank angles, R to spray a line'},
 'Udyr': {'notes': ['E MS charge stun, Q damage, W shield heal', 'R storm AoE damage'],
          'style': 'Swap stances, E stun and dive'},
 'Urgot': {'notes': ['E flip over, W sustained fire, Q slow', 'R executes below 25% and fears nearby'],
           'style': 'R executes low HP, fears nearby enemies'},
 'Varus': {'notes': ['Autos stack Blight, ranged Q detonates', 'R chain spreads root, E slows'],
           'style': 'Q long-range poke, R chains a group'},
 'Vayne': {'notes': ['Q tumble empowers autos, E condemns into walls to stun', 'R tumble grants stealth'],
           'style': 'Silver Bolts true damage shreds tanks, E near walls'},
 'Veigar': {'notes': ['E cage, then W guaranteed, Q stacks AP', 'R deals most to low HP'],
            'style': 'Full combo after E cage lands, Q minions to stack'},
 'Velkoz': {'notes': ['E knock-up, W rift, Q split for angles', 'R laser applies passive true damage'],
            'style': 'Long-range poke, 3 passive stacks = true damage'},
 'Vex': {'notes': ['E marks for passive fear, Q ranged wave, W shield triggers fear',
                   'R hit, recast to dash; resets on kill'],
         'style': 'Counters dashers; R resets on kills'},
 'Vi': {'notes': ['Q charge knock-up, E empowered autos, R locked knock-up', 'R into backline, Q out'],
        'style': "R locks the carry; can't be blocked"},
 'Viego': {'notes': ['W charge stun, Q stab, E mist MS', 'R executes low HP; possess champ on kill'],
           'style': 'Keep fighting with their kit after possessing'},
 'Viktor': {'notes': ['W stun field, E laser, Q shield', 'R storm follows enemies'],
            'style': 'E laser poke, upgrades are key'},
 'Vladimir': {'notes': ['E charged AoE, Q heal, R amplifies damage', 'W pool dodges any skill'],
              'style': 'W key skills, R burst in the group'},
 'Volibear': {'notes': ['Q charge stun, W bite twice to heal, E lightning shield',
                        'R leap in; also disables turrets'],
              'style': 'R into backline to engage'},
 'Warwick': {'notes': ['R leap suppress, Q bite, E fear nearby', "Hold Q to follow target's dash"],
             'style': 'Low-HP enemies are marked; R backline'},
 'Xayah': {'notes': ['Autos/Q leave feathers, E recalls to root', 'R untargetable to dodge, lays feathers to recall'],
           'style': 'Set up feathers, E roots a line'},
 'Xerath': {'notes': ['E stun, W center damage, Q charged long shot', 'R three long-range shots to clean up'],
            'style': "Mayhem's king of long-range poke"},
 'XinZhao': {'notes': ['E dash slow, Q third hit knocks up, W sweep', 'R knocks back and blocks ranged damage'],
             'style': 'E onto backline, R vs ranged'},
 'Yasuo': {'notes': ['Q third cast tornado after 2 stacks, into R', 'E through minions: Q becomes circle AoE'],
           'style': 'Combo R off ally knock-ups, W windwall'},
 'Yone': {'notes': ['Q third hit knocks up, R dash knocks up a line', 'E spirit form returns you after combo'],
          'style': 'E in to burst, snap back after'},
 'Yorick': {'notes': ['W wall traps, E marks, Q summons ghouls', 'R summons the Maiden'],
            'style': 'W trap enemies for ghouls to bite'},
 'Yuumi': {'notes': ['Attached Q missile, R waves root', 'E heals and gives AS to attached ally'],
           'style': "Attach to your strongest ally, don't hop off"},
 'Zac': {'notes': ['E long-range slingshot knock-up, Q pulls, R bounces', 'Q can slam two enemies together'],
         'style': 'E engage from far, pick up blobs'},
 'Zed': {'notes': ['W shadow, E slow, overlap three Q', 'R mark then full combo; mark pops at end'],
         'style': 'R the carry; swap to W/R shadow to escape'},
 'Zeri': {'notes': ['Q rapid fire, E vaults walls, W laser through walls', 'R speeds up the more you hit'],
          'style': 'E over walls to kite, sustained DPS after R'},
 'Ziggs': {'notes': ['E minefield, W satchel knockback, Q bouncing bomb', 'R long-range bombard'],
           'style': 'Mayhem long-range bomb poke'},
 'Zilean': {'notes': ['Q bomb, W reset, Q second bomb to stun', 'R revives ally on death'],
            'style': 'Double bomb stun, R on focused carry'},
 'Zoe': {'notes': ['E sleep; Q drawn far back for max damage', 'W picks up summoner spell shards'],
         'style': 'E lands, long-range Q one-shots'},
 'Zyra': {'notes': ['E root, Q seeds bloom into plants', 'R knocks up and empowers plants'],
          'style': 'Blanket the field with seeds, set up with E root'}}
